version: '3.7'

services:
  steam:
    build:
      dockerfile: Dockerfile
    ports:
     - "8084:80"
    depends_on:
     - "postgres_database"
    links:
     - postgres_database
    command: "dotnet run"



  postgres_database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_user
      - POSTGRES_USER=postgres_user
      - POSTGRES_DBNAME=steam_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data:rw"

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

volumes:
  postgres_volume_local: